name: CI
on:
  push:
    branches: [main]
  pull_request: 

jobs:
  terrafor_validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - run: terraform init
      - run: terraform ftm -check
      - run: terraform validate
      - run: terraform plan -out=tfplan